name: Build firmware
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:


jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
=======
        keyboard:
          - ergodox_ez
          - ergodox_ez/shine
          - ergodox_ez/glow
          - moonlander
          - planck/ez
          - planck/ez/glow
>>>>>>> firmware21
        keymap:
          - default
          - oryx

    steps:
    - name: Checkout QMK Firmware
<<<<<<< HEAD
      uses: actions/checkout@v4
=======
      uses: actions/checkout@v2
>>>>>>> firmware21
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Build
      id: build
      run: |
<<<<<<< HEAD
        qmk mass-compile -f manufacturer="ZSA Technology Labs" -km ${{ matrix.keymap }} -e SKIP_GIT=1
=======
        qmk compile -kb ${{ matrix.keyboard}} -km ${{ matrix.keymap }}

        TARGET="$(echo "${{ matrix.keyboard }}" | sed 's#/#_#g')_${{matrix.keymap}}"
        echo ::set-output name=artifact-name::${TARGET}
        echo "Artifact-name: ${{ steps.build.outputs.artifact-name }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "${{ steps.build.outputs.artifact-name }}"
        path: |
          *.hex
          *.bin
      continue-on-error: true
>>>>>>> firmware21
